Iter20
eugene982/url-shortener pull request #9
Opened 2023-09-04 16:57 UTC by eugene982

2023-09-05 18:16 UTC, arttet requested changes

2023-09-05 18:16 UTC, arttet commented on cmd/shortener/main.go
> +	// запуск gприложения в горутине
Please find a misprint here

2023-09-05 18:16 UTC, arttet commented on cmd/staticlint/internal/osexit/osexit.go
> +					pass.Reportf(x.Pos(), "os.Exit in main func")
Not clear message

2023-09-05 18:16 UTC, arttet commented on internal/app/application.go
> +		ReadTimeout:  time.Duration(conf.Timeout) * time.Second,
You can read `Timeout` as `time.Duration`  For example: `5s` is ok

2023-09-05 18:16 UTC, arttet commented on makefile
> +BUILD_COMMIT="Инкремент 20"
It should be a hash code

2023-09-05 18:16 UTC, arttet commented on makefile
> +	$(HOME)/go/bin/staticcheck ./...
```suggestion
	$(GOBIN)/staticcheck ./...
```

2023-09-05 18:16 UTC, arttet commented on makefile
> +	$(HOME)/go/bin/staticcheck ./...
https://www.programming-books.io/essential/go/gopath-goroot-gobin-d6da4b8481f94757bae43be1fdfa9e73

2023-09-05 18:16 UTC, arttet commented on makefile
It would be better if you rename as `Makefile`

2023-09-05 18:16 UTC, arttet commented on makefile
https://opensource.com/article/18/8/what-how-makefile

2023-09-05 18:16 UTC, arttet commented on makefile
> +test1:
Please remove duplicate code

2023-09-07 16:59 UTC, eugene982 commented on cmd/staticlint/internal/osexit/osexit.go
> +					pass.Reportf(x.Pos(), "os.Exit in main func")
ни чего умнее "call os.Exit() in main function" не придумал...

2023-09-07 17:02 UTC, eugene982 commented on makefile
> +BUILD_COMMIT="Инкремент 20"
Коммит должен быть хешем? а как мне посчитать хеш бинарника до компиляции?

2023-09-07 17:44 UTC, eugene982 commented on makefile
> +test1:
Что имеется в виду под дублированием? одинаково начало команды в тестах?

2023-09-10 08:26 UTC, arttet approved these changes

2023-09-10 08:26 UTC, arttet commented on Makefile
> +BUILD_COMMIT="Инкремент 20"
It should be a hash code

2023-09-10 08:28 UTC, arttet approved these changes

2023-09-10 08:28 UTC, arttet commented on makefile
> +BUILD_COMMIT="Инкремент 20"
https://stackoverflow.com/questions/949314/how-do-i-get-the-hash-for-the-current-commit-in-git

2023-09-10 09:26 UTC, eugene982 commented on Makefile
> +BUILD_COMMIT="Инкремент 20"
я понял, это не хеш бинарника, а гит коммита

2023-09-10 09:29 UTC, merged